source [file join [file dirname $argv0] common.exp]

send "allc 1\n"
expect -exact "+ALLC 1\r"
send "cmds 1 tid ltptest01 -i 1337\n"
expect -exact "+CMDS 1 tid ltptest01 -i 1337\r"

send "allc 2\n"
send "allc 3\n"
send "cmds 3 ltptest03 ltptest03\n"
expect "+CMDS 3 ltptest03 ltptest03\r"
send "cmds 2 fa551e80818a9ef8f55c0c90cdacad1fcf141496 syzwrap  -d /opt/ltp/testcases/bin -n fa551e80818a9ef8f55c0c90cdacad1fcf141496\n"
expect "+CMDS 2 fa551e80818a9ef8f55c0c90cdacad1fcf141496 syzwrap  -d /opt/ltp/testcases/bin -n fa551e80818a9ef8f55c0c90cdacad1fcf141496\r"

close
